[server]
enableStaticServing = true

[theme]
primaryColor = "#13aa52"           # mongodb green
backgroundColor = "#0d1b24"        # deep dark blue
secondaryBackgroundColor = "#182733" # slightly lighter dark blue
textColor = "#e8f5e9"              # light greenish text
font = "sans serif"

[theme.sidebar]
backgroundColor = "#e8e7dd"
secondaryBackgroundColor = "#ecebe3"
